using numpy module

In [ ]:
!pip install numpy #installing the module named numpy

In [ ]:
import numpy as np
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [14]:
a2=np.array([
    [1,2,3],
    [1,3,5]
    ])
print(a2+a2)

[[ 2  4  6]
 [ 2  6 10]]


In [ ]:
a3=np.array([
    [
        [1,2,3],
    [1,2,3]
    ],
    [
        [1,2,3],
    [1,2,3]
    ]
    ])
print(a3)
print(a3.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
3


In [18]:
b=np.zeros((2,3))
print(b)
print(b.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [20]:
b=np.ones((3,3))
print(b)
print(b.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [21]:
d=np.arange(0,10,2)
print(d)

[0 2 4 6 8]


In [23]:
e = np.linspace(1,3,5)
print(e)

[1.  1.5 2.  2.5 3. ]


In [30]:
a=np.array([1,2,3,4,6,7,9,8,9])
print(a[0])
print(a[len(a)-1])
print(a[2])

1
9
3


In [35]:
b=np.array([100,200,300,400,500])
print(b[-1])
print(b[-2])
print(b[-len(b)])

500
400
100


In [70]:
c=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

#print second row
print(c[1])

#print second row
print(c[:,1])

#print second row
print(c[2])

[4 5 6]
[2 5 8]
[7 8 9]


In [88]:
d=np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])
"""
print secuence 
 [[20 30]
  [60 70]]
  """
print(d[:2,2:4])
print()
#print last column
print(d[:,3])
print()

"""
print secuence 
[[ 60  70  80]
 [100 110 120]]
  """
print(d[1:3,1:3])

[[30 40]
 [70 80]]

[ 40  80 120]

[[ 60  70]
 [100 110]]


In [91]:
a=np.array([1,2,3,5,6,7])
b=np.array([6,8,9,11,12,14])
print(a+b)
print(a-b)
print(a*b)
print(np.flip(a))
print(a[::-1])

[ 7 10 12 16 18 21]
[-5 -6 -6 -6 -6 -7]
[ 6 16 27 55 72 98]
[7 6 5 3 2 1]
[7 6 5 3 2 1]


In [95]:
c=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
])
print(c[0,1,1])
print(c.ndim)

4
3
