In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
x= np.array(34)
print(x)

34


In [ ]:
print(type(x))  #Zero dimension array

<class 'numpy.ndarray'>


In [22]:
arr = np.array([1,2,3,4],ndmin=4)

print(arr)
print('Number of dimension:',arr.ndim)


[[[[1 2 3 4]]]]
Number of dimension: 4


In [23]:
print(arr[0])

[[[1 2 3 4]]]


#Slicing

In [25]:
arr = np.array([1,2,3,4,5,6,7,8])
x= arr[1:6]
print("The number find:", x)
x1 = arr[2:4:6]
print(x1)


The number find: [2 3 4 5 6]
[3]


In [ ]:
# i = integer(1,2,3)
# b = Bollean (T, F)
# u = unsigined int (0 to positive)
# f = float (1.5, 2.7)
# c = complex (1+2j)
# m = Timedelta (5 days)
# M = Date time (2025-12-21)
# O = Object (mixed data)
# S = Byte string  (b"hello")
# U = Unicode string - Hello 
# V = void

In [27]:
import numpy as np

a = np.array([1,2,3,4])
b= np.array(["Sachendra","Nawaraj","Balkrishna"])
c= np.array
print(a.dtype)
print(b.dtype)


int64
<U10
