In [7]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[1,2,3,5,5,6]])
print(f"The dimention of this matrix is {a.ndim}")
print(f"The shape of this matrix is {a.shape}")

The dimention of this matrix is 2
The shape of this matrix is (2, 6)


In [ ]:
a=np.array([[
    [1,2,3,4],
[1,2,3,4]
],[[1,2,3,4],[1,2,3,4]],])
print(f"The dimention of this matrix is {a.ndim}")
print(f"The shape of this matrix is {a.shape}")

The dimention of this matrix is 3
The shape of this matrix is (2, 2, 4)


In [9]:
b=np.array([1,2,3,4,5,6,7,8,9])
c=b.reshape(3,3)
print(c)
print(b.shape)
print(c.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(9,)
(3, 3)
