In [2]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[1,2,3,5,5,6]])
print(f"The dimention of this matrix is {a.ndim}")
print(f"The shape of this matrix is {a.shape}")

The dimention of this matrix is 2
The shape of this matrix is (2, 6)


In [10]:
a=np.array([[
    [1,2,3,4],
[1,2,3,4]
],[[1,2,3,4],[1,2,3,4]],])
print(f"The dimention of this matrix is {a.ndim}")
print(f"The shape of this matrix is {a.shape}")

The dimention of this matrix is 3
The shape of this matrix is (2, 2, 4)


In [11]:
b=np.array([1,2,3,4,5,6,7,8,9])
c=b.reshape(3,3)
print(c)
print(b.shape)
print(c.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(9,)
(3, 3)


In [24]:
arr=np.array([1,2,3,4,6,7,8])
arr[arr>5]

array([6, 7, 8])

In [22]:
are=np.array([1,2,3,5,6,7,8,9])
add=are+3
sub=are-3
mul=are*2
div=are/2
print(f"the value after addition is :{add}")
print(f"the value after subtraction is :{sub}")
print(f"the value after multiplication is :{mul}")
print(f"the value after division is :{mul}")
sum=np.mean(are)
print(f"the mean is : {sum}")
print(f"The value in arrey greater then its mean are :{are[are>sum]}")

the value after addition is :[ 4  5  6  8  9 10 11 12]
the value after subtraction is :[-2 -1  0  2  3  4  5  6]
the value after multiplication is :[ 2  4  6 10 12 14 16 18]
the value after division is :[ 2  4  6 10 12 14 16 18]
the mean is : 5.125
The value in arrey greater then its mean are :[6 7 8 9]


In [37]:
import numpy as np
a=np.array([1,2,34,56,78,90,234567,89,87654,33456,78])
np.sin(a)
np.cos(a)
np.tan(a)
np.log(a)

array([ 0.        ,  0.69314718,  3.52636052,  4.02535169,  4.35670883,
        4.49980967, 12.36549654,  4.48863637, 11.38115253, 10.41798642,
        4.35670883])