In [1]:

import numpy as np

print("NumPy Assignment Solutions")


NumPy Assignment Solutions


## Section A: Data Types

In [3]:

# Q1
arr_int = np.array([1, 2, 3], dtype="int32")
arr_float = np.array([1.1, 2.2, 3.3], dtype="float64")
arr_bool = np.array([True, False, True], dtype="bool")
arr_date = np.array(['2026-01-01'], dtype='datetime64')

print(arr_int)
print(arr_float)
print(arr_bool)
print(arr_date)

# Q2
arr = np.array([1, 2, 3, 4], dtype=np.float64)
print(arr)

# Q3
arr_dtype = np.array([1.5, 2.5, 3.5])
print(arr_dtype.dtype)

# Q4
dates = np.arange('2026-01-01', '2026-01-08', dtype='datetime64[D]')
print(dates)

# Q5
print("dtype is important because it controls memory usage, speed, and calculations.")


[1 2 3]
[1.1 2.2 3.3]
[ True False  True]
['2026-01-01']
[1. 2. 3. 4.]
float64
['2026-01-01' '2026-01-02' '2026-01-03' '2026-01-04' '2026-01-05'
 '2026-01-06' '2026-01-07']
dtype is important because it controls memory usage, speed, and calculations.


## Section B: Vectorization

In [4]:

# Q1
prices = np.array([100, 200, 300, 400])
taxed_prices = prices * 1.13
print(taxed_prices)

# Q2
salaries = np.array([30000, 50000, 70000])
new_salaries = salaries * 1.10
print(new_salaries)

# Q3
celsius = np.array([0, 20, 30, 40])
fahrenheit = (celsius * 9/5) + 32
print(fahrenheit)

# Q4
discounted = prices * 0.80
print(discounted)

# Q5
salary = np.array([40000, 55000, 70000])
bonus = np.where(salary > 50000, salary * 0.15, salary * 0.05)
print(bonus)


[113. 226. 339. 452.]
[33000. 55000. 77000.]
[ 32.  68.  86. 104.]
[ 80. 160. 240. 320.]
[ 2000.  8250. 10500.]


## Section C: Broadcasting

In [5]:

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Q1
print(matrix + 10)

# Q2
vector = np.array([10, 20, 30])
print(matrix + vector)

# Q3
column_vector = np.array([[2], [3]])
print(matrix * column_vector)

# Q4
row_vector = np.array([1, 2, 3])
print(matrix + row_vector)

# Q5
print("Broadcasting allows NumPy arrays with different shapes to work together.")


[[11 12 13]
 [14 15 16]]
[[11 22 33]
 [14 25 36]]
[[ 2  4  6]
 [12 15 18]]
[[2 4 6]
 [5 7 9]]
Broadcasting allows NumPy arrays with different shapes to work together.


## Section D: Mathematical Functions

In [6]:

sales = np.array([120, 140, 200, 250, 300])

# Q1
print("Sum:", np.sum(sales))
print("Mean:", np.mean(sales))
print("Median:", np.median(sales))

# Q2
print("Standard Deviation:", np.std(sales))
print("Variance:", np.var(sales))

# Q3
print("Min:", np.min(sales))
print("Max:", np.max(sales))

# Q4
print("Square Root:", np.sqrt(sales))

# Q5
print("Log Values:", np.log(sales))

# Q6
print("Cumulative Sum:", np.cumsum(sales))


Sum: 1010
Mean: 202.0
Median: 200.0
Standard Deviation: 67.05221845696084
Variance: 4496.0
Min: 120
Max: 300
Square Root: [10.95445115 11.83215957 14.14213562 15.8113883  17.32050808]
Log Values: [4.78749174 4.94164242 5.29831737 5.52146092 5.70378247]
Cumulative Sum: [ 120  260  460  710 1010]


## Section E: Axis

In [7]:

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Q1
print("Row-wise Sum:", np.sum(arr, axis=1))

# Q2
print("Column-wise Sum:", np.sum(arr, axis=0))

# Q3
print("Row-wise Mean:", np.mean(arr, axis=1))

# Q4
print("Column-wise Max:", np.max(arr, axis=0))

# Q5
print("axis=0 works column-wise")
print("axis=1 works row-wise")


Row-wise Sum: [ 60 150]
Column-wise Sum: [50 70 90]
Row-wise Mean: [20. 50.]
Column-wise Max: [40 50 60]
axis=0 works column-wise
axis=1 works row-wise


## Section F: Filtering & Conditions

In [8]:

marks = np.array([45, 76, 88, 34, 92, 60])

# Q1
print(marks[marks > 60])

# Q2
print(marks[marks < 50])

# Q3
updated_marks = np.where(marks < 40, 40, marks)
print(updated_marks)

# Q4
result = np.where(marks >= 40, "Pass", "Fail")
print(result)

# Q5
print(marks[marks % 2 == 0])


[76 88 92]
[45 34]
[45 76 88 40 92 60]
['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']
[76 88 34 92 60]


## Section G: Percentile, Quantile, Correlation

In [9]:

data = np.array([10, 20, 30, 40, 50, 60, 70])

# Q1
print("25th Percentile:", np.percentile(data, 25))

# Q2
print("Median:", np.percentile(data, 50))

# Q3
print("Quantile 0.75:", np.quantile(data, 0.75))

# Q4
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

correlation = np.corrcoef(x, y)
print(correlation)

# Q5
print("Correlation close to 1 means strong positive relationship.")


25th Percentile: 25.0
Median: 40.0
Quantile 0.75: 55.0
[[1. 1.]
 [1. 1.]]
Correlation close to 1 means strong positive relationship.


## Section H: Real-world Case Study

In [10]:

sales = np.array([
    [200, 300, 250],
    [400, 500, 450],
    [150, 250, 350]
])

# Q1
print("Total Sales Per Store:", np.sum(sales, axis=1))

# Q2
print("Total Sales Per Month:", np.sum(sales, axis=0))

# Q3
print("Average Monthly Sales:", np.mean(sales, axis=0))

# Q4
print("Highest Sales:", np.max(sales))

# Q5
store_totals = np.sum(sales, axis=1)
print("Stores with sales > 1000:", store_totals[store_totals > 1000])


Total Sales Per Store: [ 750 1350  750]
Total Sales Per Month: [ 750 1050 1050]
Average Monthly Sales: [250. 350. 350.]
Highest Sales: 500
Stores with sales > 1000: [1350]


## Mini Project: Restaurant Sales Analysis

In [11]:

sales = np.array([
    [1200, 1500, 1100, 1700],
    [1000, 1300, 1400, 1600],
    [900, 1100, 1000, 1500]
])

# Task 1
branch_sales = np.sum(sales, axis=1)
print("Total Sales Per Branch:", branch_sales)

# Task 2
branches = ["Branch A", "Branch B", "Branch C"]
highest_branch = branches[np.argmax(branch_sales)]
print("Highest Branch:", highest_branch)

# Task 3
print("Average Weekly Sales:", np.mean(sales, axis=0))

# Task 4
weeks = ["Week1", "Week2", "Week3", "Week4"]
highest_week = weeks[np.argmax(np.sum(sales, axis=0))]
print("Week with Highest Revenue:", highest_week)

# Task 5
taxed_sales = sales * 1.13
print("Sales After 13% Tax:")
print(taxed_sales)


Total Sales Per Branch: [5500 5300 4500]
Highest Branch: Branch A
Average Weekly Sales: [1033.33333333 1300.         1166.66666667 1600.        ]
Week with Highest Revenue: Week4
Sales After 13% Tax:
[[1356. 1695. 1243. 1921.]
 [1130. 1469. 1582. 1808.]
 [1017. 1243. 1130. 1695.]]
